packages:
  - 'frontend/*'
  - 'backend/*'
  - 'packages/*'

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - 'esbuild'
  - 'prisma'

minimumReleaseAgeExclude:
  - '@tanstack/query-core'
  - '@tanstack/query-devtools'
  - '@tanstack/react-query-devtools'
  - '@tanstack/react-query'

allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  esbuild: true
  prisma: true
